### PR TITLE
Delete old templates

### PR DESCRIPTION
**Pull request by gavinleeedwards**
# Has the DDL schema changed?
No schema change

# Motivation and Context
Delete all old email and file templates

# What has changed
Patch script to delete all CRIS related templates, plus a rollback script in case we need to bring them back.

# How to test?
Check that it all looks ok.  It's more or less the reverse of patch 800, plus 2 others.

# Links
https://trello.com/c/QUIXn8uY

### CODE REVIEW

**Comment by gavinleeedwards** [comment]
[Add DDL to delete old templates (3)](https://trello.com/c/QUIXn8uY/1135-add-ddl-to-delete-old-templates-3)

**Comment by gavinleeedwards** [comment]
[Add DDL to delete old templates (3)](https://trello.com/c/QUIXn8uY/1135-add-ddl-to-delete-old-templates-3)

**Review by AdamHawtin — CHANGES_REQUESTED** [review]
The templates also need to be deleted from the ground zero scripts https://github.com/ONSdigital/ssdc-rm-ddl/tree/main/groundzero_ddl/packcode_templates

**Review by ryangrundy7 — CHANGES_REQUESTED** [review]
I think you need to remove it from the dev postgres image https://github.com/ONSdigital/ssdc-rm-ddl/blob/main/dev-common-postgres-image/init.sql#L598-L615

**Comment by gavinleeedwards** [comment]
I've intentionally left the packcode_template files as blank placeholder files to save us removing the code from `build_init_script.sh`, only to put it back in in a few weeks.

**Review by ryangrundy7 — APPROVED** [review]

**Review by AdamHawtin — APPROVED** [review]
LGTM 👍

**Pull request merged**
